# Generated by Django 4.1.5 on 2023-01-22 10:07

import backend.api.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdTimestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedTimestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='unknown', max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('brand', models.CharField(default='unknown', max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('price', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('product_SSN', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('FAN', 'FAN'), ('TURBOCHARGER', 'TURBOCHARGER'), ('ACCESSORIES', 'ACCESSORIES'), ('HOUSINGS', 'HOUSINGS')], default='TURBOCHARGER', max_length=12, verbose_name='Category')),
                ('description', models.TextField(max_length=20, validators=[django.core.validators.MinLengthValidator(5)])),
                ('image', models.ImageField(upload_to='products', validators=[backend.api.common.validators.MaxFileSizeValidator(5)])),
                ('rating', models.FloatField(default=0.1)),
                ('countInStock', models.IntegerField(default=0)),
                ('numReviews', models.IntegerField(default=0)),
            ],
        ),
    ]
