# Generated by Django 4.1.5 on 2023-01-22 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
