# Generated by Django 4.1.5 on 2023-01-23 06:42

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productcategory_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=100, validators=[django.core.validators.MinLengthValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
